import = [
	'~/.config/alacritty/themes/themes/catppuccin_mocha.toml'
]

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
duration = 0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "UbuntuMono Nerd Font"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
padding = { x = 10, y=10}
dynamic_padding = true
decorations = "None"

[cursor]
style = {shape = "Beam", blinking= "on" }
