
[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
duration = 0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "UbuntuMono Nerd Font"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[terminal.shell]
program = "/usr/bin/tmux"

[window]
padding = { x = 10, y=10}
dynamic_padding = true
decorations = "None"

[general]

live_config_reload = true
import = [
	'~/.config/alacritty/themes/themes/catppuccin_mocha.toml'
]

[terminal]
